Fix_CI_Endless_Run

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -13,7 +13,7 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [18.x, 20.x, 22.x]
+        node-version: [20.x]
 
     steps:
     - uses: actions/checkout@v4
@@ -32,5 +32,13 @@ jobs:
         echo "SERVER_HOST_DB_NAME=${{ secrets.SERVER_HOST_DB_NAME }}" >> .env
         echo "SERVER_JSWTOKEN=${{ secrets.SERVER_JSWTOKEN }}" >> .env
     - run: npm ci
-    - run: npm run start
+    - run: npm run start &
+    - name: Wait for Server to Start
+      run: |
+        sleep 5
+        if curl -f http://localhost:3000; then
+          echo "Server is running successfully."
+        else
+          echo "Server failed to start." && exit 1
+        fi
     - run: npm test
